//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilePhones
    {
        public int MobilePhoneId { get; set; }
        public Nullable<int> PhoneModelId { get; set; }
        public string IMEI { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string IssueDescription { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PhoneModels PhoneModels { get; set; }
    }
}
